import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from '@/providers/NextAuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import ReduxProvider from '@/redux/ReduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Intanuay Job Fair',
  description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NextAuthProvider session={ session }>
            <NavBar />
            {children}
          </NextAuthProvider> 
        </ReduxProvider> 
      </body>
    </html>
  )
}
